plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.0'
  id 'io.spring.dependency-management' version '1.1.7'
}

group = 'cn.jee'
version = '0.0.1-SNAPSHOT'
description = 'jee2026_exam_stu'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  maven { url='https://maven.aliyun.com/repository/public/' }
  maven { url='https://maven.aliyun.com/repository/spring/' }
  maven { url='https://mirrors.huaweicloud.com/repository/maven/' }
  mavenCentral()
}

dependencies {

  implementation 'org.springframework.boot:spring-boot-starter-web'

  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

  implementation 'org.springframework.boot:spring-boot-starter-validation'

  runtimeOnly 'org.hsqldb:hsqldb'

  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'

  testCompileOnly 'org.projectlombok:lombok'
  testAnnotationProcessor 'org.projectlombok:lombok'

  testImplementation 'org.springframework.boot:spring-boot-starter-test'

  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
  useJUnitPlatform()
}

tasks.register('dbStart', JavaExec) {
  group = "hsqldb"
  classpath = sourceSets.main.runtimeClasspath
  workingDir = file("db")
  mainClass = 'org.hsqldb.server.Server'
}

tasks.register('dbManager', JavaExec) {
  group = "hsqldb"
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'org.hsqldb.util.DatabaseManagerSwing'
}

tasks.register('dbShutdown') {
  group = 'hsqldb'

  doLast {
    try {
      ant.sql(
        driver: 'org.hsqldb.jdbc.JDBCDriver',
        url: 'jdbc:hsqldb:hsql://localhost/',
        userid: 'SA',
        password: '',
        onerror: 'abort',
        classpath: configurations.runtimeClasspath.asPath
      ) {
        transaction("SHUTDOWN;")
      }

      logger.lifecycle("数据库关闭成功")

    } catch(Exception ex) {

      logger.lifecycle("dbShutdown 执行完成")
    }
  }
}