plugins {
  id 'java'
  id 'org.springframework.boot' version '4.0.3'
  id 'io.spring.dependency-management' version '1.1.7'
}

group = 'cn.jee'
version = '0.0.1-SNAPSHOT'
description = 'jee2026_exam_stu'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  maven { url='https://maven.aliyun.com/repository/public/' }
  maven { url='https://maven.aliyun.com/repository/spring/'}
  maven {url='https://mirrors.huaweicloud.com/repository/maven/'}
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
  implementation 'org.springframework.boot:spring-boot-starter-webmvc'
  compileOnly 'org.projectlombok:lombok'
  runtimeOnly 'org.hsqldb:hsqldb'
  annotationProcessor 'org.projectlombok:lombok'
  testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
  testCompileOnly 'org.projectlombok:lombok'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testAnnotationProcessor 'org.projectlombok:lombok'

  implementation 'org.springframework.boot:spring-boot-starter-validation'
}

tasks.named('test') {
  useJUnitPlatform()
}
tasks.register('dbStart', JavaExec) {
  group("hsqldb")
  classpath = sourceSets.main.runtimeClasspath
  workingDir("db")
  mainClass = 'org.hsqldb.server.Server'
}
tasks.register('dbManager', JavaExec) {
  group("hsqldb")
  classpath = sourceSets.main.runtimeClasspath
  mainClass = 'org.hsqldb.util.DatabaseManagerSwing'
}
tasks.register('dbShutdown') {
  description = 'Execute SQL script using HSQLDB'
  group = 'hsqldb'
  doLast {
    try{
      ant.sql(
        driver: 'org.hsqldb.jdbc.JDBCDriver',
        url: 'jdbc:hsqldb:hsql://localhost/',
        userid: 'SA',
        password: '',
        onerror: 'abort',
        encoding: 'UTF-8',
        delimiter: ';',
        delimitertype: 'row',
        classpath: configurations.runtimeClasspath.asPath,
        "shutdown"
      )
      logger.lifecycle("✅ SQL 执行成功！")
    }catch(Exception ex){
      logger.lifecycle("✅ dbShutdown 执行成功！")
    }
  }
}