spring:
  datasource:
    url: jdbc:hsqldb:file:./data/moviedb;shutdown=true;hsqldb.lock_file=false
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: 123456

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

server:
  port: 8080