spring.application.name=jee2026_exam_stu

# ========== ???? ==========
spring.output.ansi.enabled=always
logging.level.web=debug
logging.level.cn.jee=debug

# ========== ??? ==========
spring.datasource.url=jdbc:hsqldb:file:./data/moviedb;shutdown=true;hsqldb.lock_file=false
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=123456

# ========== ????? data.sql ? Hibernate ?????? ==========
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true

# SQL ???????????
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.stat=debug

# ========== MVC ==========
spring.mvc.log-request-details=true

# ========== Thymeleaf ==========
spring.thymeleaf.cache=false

# ========== ???? ==========
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=true
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

# ========== ??? ==========
server.port=8080